config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :prototypes do
    resources :ranking ,only: [:index]
    resources :latest ,only: [:index]
  end
  resources :prototypes, only: [:new, :create, :show]
  namespace :prototypes, path: 'prototypes/:id' do
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show]
  root to:  'prototypes/latest#index'
  get 'users/:id' => 'users#show'
  resources :likes, only: [:create, :destroy]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  acts_in_relation role: :action, source: :user, target: :prototype
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :list
  belongs_to :user
  has_many :comments
  has_many :captured_images
  acts_in_relation role: :target, source: :user, action: :like
  accepts_nested_attributes_for :captured_images
end

app/models/user.rb
class User < ActiveRecord::Base
  #association
  has_many :prototypes
  has_many :comments
  acts_in_relation role: :source, target: :prototype, action: :like
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters ,if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :work, :member, :profile, :avatar)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    current_user.like(@prototype)
    @like_count = @prototype.likers.length
    render json: {like_count: @like_count}
  end
  def destroy
    @prototype = Prototype.find(params[:prototype_id])
    current_user.unlike(@prototype)
    @like_count = @prototype.likers.length
    render json:{like_count: @like_count}
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController

  def new
  end
  def create
    @prototype = Prototype.find(params[:id])
    @prototype.comments.build(text: create_params[:text], user_id: current_user.id).save
    # redirect_to prototype_path
  end
  private
  def create_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/prototypes/latest_controller.rb
class Prototypes::LatestController < ApplicationController

  def index
    @prototypes = Prototype.order('created_at DESC').page(params[:page]).per(5)
  end
end

app/controllers/prototypes/ranking_controller.rb
class Prototypes::RankingController < ApplicationController

  def index
    prototype_ids =Like.group(:target_prototype_id).order("count_target_prototype_id DESC").count(:target_prototype_id).keys
    @rankings = Prototype.where(id: prototype_ids).page(params[:page]).per(5)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def new
    @prototype=Prototype.new
    @prototype.captured_images.build
  end
  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @sub_images = @prototype.captured_images.where(property: "sub")
  end
  def create
    current_user.prototypes.build(create_params).save
    redirect_to root_path
  end
  private
  def create_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :genre, :url,captured_images_attributes: [:image,:property]).merge(tag_list: params[:list][:tag])
  end
  def propetry_params
    params.require(:prototype).permit(captured_images_attributes: [:property])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(100)
  end
  def show
    @tag = ActsAsTaggableOn::Tag.find_by(params[:id])
    proto_tags = ActsAsTaggableOn::Tagging.where(tag_id: params[:id])
    @prototypes = Prototype.where(id:proto_tags.map{|proto_tag| Prototype.find(proto_tag.taggable_id)}).page(params[:page]).per(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @prototypes = current_user.prototypes.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      //not login
      %ul.nav.navbar-nav.navbar-right
        %li
          - if user_signed_in?
            .btn.btn-primary.navbar-btn
              = link_to "Logout", destroy_user_session_path, method: :delete
            .btn.btn-primary.navbar-btn
              %a{href: "/users/#{current_user.id}"}
                YourPage
          -else
            .btn.btn-primary.navbar-btn
              %a{href: "/users/sign_in"}
                Get Started
      //login
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown",id: "dropdownMenu1", href: "#", role: "button"}
            -if user_signed_in?
              =current_user.name
            -else
              %p guest
            %span.caret
          %ul.dropdown-menu{role: "menu","aria-labelledby" => "dropdownMenu1"}
            %li
              %a{role: "menuitem", tabindex: "-1",href: "#"} Profile Edit
            %li
              %a{role: "menuitem",tabindex: "-1", href: "#"} Logout
            }
        %li
          .btn.btn-primary.navbar-btn
            %a{href: "/prototypes/new"}
              New Proto

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .dower
      = yield
    = render "layouts/footer"

app/views/prototypes/_form.html.haml
%form.form-inline{role: "form"}
  %h4 Write a comment
  .row
    .form-group.col-md-10
      %textarea.form-control{placeholder: "Your comments", rows: "3"}
    .form-group.col-md-2
      %button.btn.btn-primary Comment

app/views/prototypes/_form.html.slim
= form_for @prototype do |f|
  - if @prototype.errors.any?
    #error_explanation
      h2 = "#{pluralize(@prototype.errors.count, "error")} prohibited this prototype from being saved:"
      ul
        - @prototype.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_area :title
  .field
    = f.label :introduction
    = f.text_area :introduction
  .field
    = f.label :genre
    = f.text_area :genre
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :github
    = f.text_area :github
  .field
    = f.label :url
    = f.text_area :url
  .actions = f.submit

app/views/prototypes/comments/_comment.html.haml
.media
  .media-left
    %a{href: "/users/#{comment.user.id}"}
      %img.media-object{alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "#{comment.user.avatar.url}", style: "width: 64px; height: 64px;"}/
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{href: "#top-aligned-media"}
        %span.anchorjs-icon
    %p
      =comment.text
    %br

app/views/prototypes/comments/_form.html.haml
- model_class = Comment
.form-inline{role: "form"}
  = form_for [:prototypes, @comment ], remote: true, data: { no_turbolink: true } do |f|
    %h4 Write a comment
    .row
      .form-group.col-md-10
        = f.text_area :text, placeholder: "Your comments", rows: "3",id: "comment_field", class: "form-control"
      .form-group.col-md-2
        =f.submit class: "btn btn-primary"

app/views/prototypes/comments/create.js.erb
$('#comment_field').val('')
$('#comments').html(
  '<%= j(render partial: 'prototypes/comments/comment', collection: @prototype.comments) %>'
);

app/views/prototypes/edit.html.slim
h1 Editing prototype

== render 'form'

= link_to 'Show', @prototype
'|
= link_to 'Back', prototypes_path

app/views/prototypes/index.html.slim
h1 Listing prototypes

table
  thead
    tr
      th Title
      th Introduction
      th Genre
      th User
      th Github
      th Url
      th
      th
      th

  tbody
    - @prototypes.each do |prototype|
      tr
        td = prototype.title
        td = prototype.introduction
        td = prototype.genre
        td = prototype.user_id
        td = prototype.github
        td = prototype.url
        td = link_to 'Show', prototype
        td = link_to 'Edit', edit_prototype_path(prototype)
        td = link_to 'Destroy', prototype, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Prototype', new_prototype_path

app/views/prototypes/latest/_latest.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{href: "/prototypes/#{latest.id}"}
      = image_tag("#{latest.captured_images.first.image.url}")
      .caption
        %h3
          = latest.title
        .proto-meta
          .proto-user
            %a{href: "#"}
              = "by #{latest.user.name}"
          .proto-posted
            =latest.created_at.strftime("%Y/%m/%d(#{%w(Sun Mon Tue Wed Thu Fri Sat)[latest.created_at.wday]})")
        %ul.proto-tag-list.list-inline
          - latest.tag_list.each do |tag|
            - tag_id = ActsAsTaggableOn::Tag.find_by(name: tag)
            %li
              = link_to tag, tag_path(tag_id),class: "btn btn-default"

app/views/prototypes/latest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "/prototypes/ranking"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "/prototypes/latest"} Newest PROTO
      %button{type: "button", class: "btn btn-default col-lg-1", onclick: "location.href='/tags/'"} View Tags
.container.proto-list
  .row
    = render partial: "latest",collection: @prototypes

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :title ,placeholder: "Title"
      .row
        .col-md-12
          = f.fields_for :captured_images do |captured_image|
            .cover-image-upload.img_input
              = captured_image.hidden_field :property, value: "main"
              = captured_image.file_field :image
              = image_tag "", width: "100%", height: "100%", style: "display: none;"
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              = f.fields_for :captured_images do |captured_image|
                .image-upload.img_input
                  = captured_image.hidden_field :property, value: "sub"
                  = captured_image.file_field :image
                  = image_tag "", width: "100%", height: "100%", style: "display: none;"
          %ul.proto-sub-list.list-group
            %li.list-group-item.col-md-4
              = f.fields_for :captured_images do |captured_image|
                .image-upload.img_input
                  = captured_image.hidden_field :property, value: "sub"
                  = captured_image.file_field :image
                  = image_tag "", width: "100%", height: "100%", style: "display: none;"
          %li.list-group-item.col-md-4
            .image-upload-plus#add_image
              %span
                +
      .row.proto-description
        .col-md-12
          =f.text_field  :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          =f.text_area :concept ,cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              =text_field_tag "list[tag][]", "",  placeholder: "ex)science"
            .col-md-3
              =text_field_tag "list[tag][]", "", placeholder: "ex)interia"
            .col-md-3
              =text_field_tag "list[tag][]", "", placeholder: "ex)life"
      .row.text-center.proto-btn
        = f.submit 'いったれ！！', data: { confirm: "新規作成しますか？？", commit: "新規作成", cancel: "編集する"},class: "btn btn-lg btn-primary btn-block new_comfirm", title: "新規作成"

app/views/prototypes/new.html.slim
h1 New prototype

== render 'form'

= link_to 'Back', prototypes_path

app/views/prototypes/ranking/_ranking.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    %a{href: "/prototypes/#{ranking.id}"}
      = image_tag("#{ranking.captured_images.first.image.url}")
      .caption
        %h3
          = ranking.title
        .proto-meta
          .proto-user
            %a{href: "#"}
              = "by #{ranking.user.name}"
          .proto-posted
            Apr 26
        %ul.proto-tag-list.list-inline
          - ranking.tag_list.each do |tag|
            - tag_id = ActsAsTaggableOn::Tag.find_by(name: tag)
            %li
              = link_to tag, tag_path(tag_id),class: "btn btn-default"

app/views/prototypes/ranking/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "/prototypes/ranking"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "/prototypes/latest"} Newest PROTO
      %a.btn.btn-default.col-lg-1{href: "/tags"} View Tags
.container.proto-list
  .row
    =render partial: "ranking",collection: @rankings

.text-center
  %ul.pagination
    = paginate @rankings

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          %a{href: ""}
            %img.media-object{alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "#{@prototype.user.avatar.url}", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.user.name
          .proto-user
            %a{href: "/users/#{@prototype.user.id}"} by User
            %span.degree "#{@prototype.user.profile} #{@prototype.user.work}"
    .col-md-6.text-right
      %button.btn.btn-default{id: (@like_status) ? "like" : "unlike",data: {id: @prototype.id}}
        -if current_user.liking?(@prototype)
          = image_tag("icon_heart_on.svg")
        -else
          = image_tag("icon_heart_off.svg")
        Like
        %span.num
          = @prototype.likers.length
  .row
    .col-md-9
      = image_tag("#{@prototype.captured_images.first.image.url}", class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @sub_images.each do |sub_image|
          %li.list-group-item
            = image_tag("#{sub_image.image.url}", class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p #{@prototype.catch_copy}
    .col-md-6
      %h4 Concept
      %p #{@prototype.concept}
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |tag|
          - tag_id = ActsAsTaggableOn::Tag.find_by(name: tag)
          %li
            = link_to tag, tag_path(tag_id), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = "(#{@prototype.comments.length})"
    .col-md-8
      #comments
        = render partial: "prototypes/comments/comment", collection: @prototype.comments
      = render partial: "prototypes/comments/form"

app/views/prototypes/show.html.slim
p#notice = notice

p
  strong Title:
  = @prototype.title
p
  strong Introduction:
  = @prototype.introduction
p
  strong Genre:
  = @prototype.genre
p
  strong User:
  = @prototype.user_id
p
  strong Github:
  = @prototype.github
p
  strong Url:
  = @prototype.url

= link_to 'Edit', edit_prototype_path(@prototype)
'|
= link_to 'Back', prototypes_path

app/views/tags/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "/prototypes/ranking"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "/prototypes/latest"} Newest PROTO
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags
.container.proto-list
  .row
    - @tags.each do |tag|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          %button{onclick: "location.href='/tags/#{tag.id}'", style: "width: 100%; height: 50px; font-size: 2rem; font-weight: 300; padding-bottom: 3px; color: #999; background-color: #eee;", class: "btn btn-tag"}  #{tag.name}
          .tag-meta
            %a{href: "/tags/#{tag.id}", style: "display: block; font-size: 1.3rem; border-radius: 2px; margin: 0 -2px 2px;", class: "label label-default tag-list-number"}
              #{tag.taggings_count}
              %i Projects

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "/prototypes/ranking"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "/prototypes/latest"} Newest PROTO
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags
.container
  .row
    .col-sm-12.proto-content
      .thumbnail
        %button{style: "width: 100%; height: 50px; font-size: 2rem; font-weight: 300; padding-bottom: 3px; color: #999; background-color: #eee;", class: "btn btn-tag"} #{@tag}
        .tag-meta
          %a{href: "#", style: "display: block; font-size: 1.3rem; border-radius: 2px; margin: 0 -2px 2px;", class: "label label-default tag-list-number"}
            #{@tag.taggings_count}
            %i Projects
.container.proto-list
  .row
    - @prototypes.each do |prototype|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          %a{href: "/prototypes/#{prototype.id}"}
            = image_tag("#{prototype.captured_images.first.image.url}")
            .caption
              %h3 #{prototype.title}
              .proto-meta
                .proto-user
                  %a{href: "#"} by #{prototype.user.name}
                .proto-posted
                  =prototype.created_at.strftime("%Y/%m/%d(#{%w(Sun Mon Tue Wed Thu Fri Sat)[prototype.created_at.wday]})")
              %ul.proto-tag-list.list-inline
                - prototype.tag_list.each do |tag|
                  -tag_id = ActsAsTaggableOn::Tag.find_by(name: tag)
                  %li
                    = link_to tag, tag_path(tag_id), class: "btn btn-default"
.text-center
  %ul.pagination
    = paginate @prototypes

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{href: "#"}
          %img.media-object{alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "#{current_user.avatar.url}", style: "width: 64px; height: 64px;"}/

      .media-body
        %h4#top-aligned-media.media-heading
          =current_user.name
          %span.label.label-default.project-number
            =@prototypes.length
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p 
              =current_user.profile
          .col-md-6
            %h4 Works
            %p 
              =current_user.work
          .col-md-6
            %a{href: "#{current_user.github}"}
              =current_user.name+'\'Github'
.container.proto-list
  .row
    - @prototypes.each do |prototype|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          %a{href: "/prototypes/#{prototype.id}"}
            = image_tag("#{prototype.captured_images.first.image.url}")
            .caption
              %h3 
                = prototype.title
              .proto-meta
                .proto-date
                  =prototype.created_at.strftime("%Y/%m/%d(#{%w(Sun Mon Tue Wed Thu Fri Sat)[prototype.created_at.wday]})")
              %ul.proto-tag-list.list-inline
                - prototype.tag_list.each do |tag|
                  - tag_id = ActsAsTaggableOn::Tag.find_by(name: tag)
                  %li
                    = link_to tag, tag_path(tag_id),class: "btn btn-default"
.text-center
  %ul.pagination
    = paginate @prototypes